version: 2
jobs:
  build:
    working_directory: ~/multiple-bundles-webpack-plugin
    docker:
      - image: circleci/node:8.16
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Run JS Audits
          command: npm run lint
      - run:
          name: code-coverage
          command: 'npm run test:coverage'